---
root: true

env:
  browser: true
  es6: true

settings:
  ecmascript: 6

plugins:
  - vue

parser:
  "babel-eslint"

extends:
  - airbnb

rules:
  strict: 2
  quotes:
    - 2
    - single
  react/require-default-props: 0
  no-sparse-arrays: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-unused-vars: 0
  no-mixed-spaces-and-tabs: 0
  no-tabs: 0
  consistent-return: 0
  semi: 0
  jsx-a11y/no-static-element-interactions: 0
  no-confusing-arrow: 0
